// <auto-generated />
using System;
using MOM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MOM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("MOM.Models.DepartmentModel", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MOM.Models.MeetingMemberModel", b =>
                {
                    b.Property<int>("MeetingMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetingID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<int>("StaffID")
                        .HasColumnType("INTEGER");

                    b.HasKey("MeetingMemberID");

                    b.HasIndex("MeetingID");

                    b.HasIndex("StaffID");

                    b.ToTable("MeetingMembers");
                });

            modelBuilder.Entity("MOM.Models.MeetingStaffModel", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("StaffID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("MeetingStaff");
                });

            modelBuilder.Entity("MOM.Models.MeetingTypeModel", b =>
                {
                    b.Property<int>("MeetingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeetingTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("MeetingTypeId");

                    b.ToTable("MeetingTypes");
                });

            modelBuilder.Entity("MOM.Models.MeetingVenueModel", b =>
                {
                    b.Property<int>("MeetingVenueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MeetingVenueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.HasKey("MeetingVenueID");

                    b.ToTable("MeetingVenues");
                });

            modelBuilder.Entity("MOM.Models.MeetingsModel", b =>
                {
                    b.Property<int>("MeetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CancellationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeetingDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("MeetingTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetingVenueId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.HasKey("MeetingId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MeetingTypeId");

                    b.HasIndex("MeetingVenueId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("MOM.Models.MeetingMemberModel", b =>
                {
                    b.HasOne("MOM.Models.MeetingsModel", "Meeting")
                        .WithMany("MeetingMembers")
                        .HasForeignKey("MeetingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MOM.Models.MeetingStaffModel", "Staff")
                        .WithMany("MeetingMembers")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("MOM.Models.MeetingStaffModel", b =>
                {
                    b.HasOne("MOM.Models.DepartmentModel", "Department")
                        .WithMany("Staff")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MOM.Models.MeetingsModel", b =>
                {
                    b.HasOne("MOM.Models.DepartmentModel", "Department")
                        .WithMany("Meetings")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("MOM.Models.MeetingTypeModel", "MeetingType")
                        .WithMany("Meetings")
                        .HasForeignKey("MeetingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MOM.Models.MeetingVenueModel", "Venue")
                        .WithMany("Meetings")
                        .HasForeignKey("MeetingVenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("MeetingType");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("MOM.Models.DepartmentModel", b =>
                {
                    b.Navigation("Meetings");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("MOM.Models.MeetingStaffModel", b =>
                {
                    b.Navigation("MeetingMembers");
                });

            modelBuilder.Entity("MOM.Models.MeetingTypeModel", b =>
                {
                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("MOM.Models.MeetingVenueModel", b =>
                {
                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("MOM.Models.MeetingsModel", b =>
                {
                    b.Navigation("MeetingMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
